const resources = {
  fonts: {
    Onest: require("../assets/fonts/Onest/static/Onest-Regular.ttf"),
    "Onest-Bold": require("../assets/fonts/Onest/static/Onest-Bold.ttf"),
    "Onest-Light": require("../assets/fonts/Onest/static/Onest-Light.ttf"),
    "Onest-ExtraBold": require("../assets/fonts/Onest/static/Onest-ExtraBold.ttf"),
    "Onest-ExtraLight": require("../assets/fonts/Onest/static/Onest-ExtraLight.ttf"),
    "Onest-SemiBold": require("../assets/fonts/Onest/static/Onest-SemiBold.ttf"),
    "Onest-Thin": require("../assets/fonts/Onest/static/Onest-Thin.ttf"),
    "Onest-Medium": require("../assets/fonts/Onest/static/Onest-Medium.ttf"),
    "Onest-Black": require("../assets/fonts/Onest/static/Onest-Black.ttf"),
    Roboto: require("../assets/fonts/Roboto/static/Roboto-Regular.ttf"),
    "Roboto-Bold": require("../assets/fonts/Roboto/static/Roboto-Bold.ttf"),
    "Roboto-Light": require("../assets/fonts/Roboto/static/Roboto-Light.ttf"),
    "Roboto-ExtraBold": require("../assets/fonts/Roboto/static/Roboto-ExtraBold.ttf"),
    "Roboto-ExtraLight": require("../assets/fonts/Roboto/static/Roboto-ExtraLight.ttf"),
    "Roboto-SemiBold": require("../assets/fonts/Roboto/static/Roboto-SemiBold.ttf"),
    "Roboto-Thin": require("../assets/fonts/Roboto/static/Roboto-Thin.ttf"),
    "Roboto-Medium": require("../assets/fonts/Roboto/static/Roboto-Medium.ttf"),
    "Roboto-Black": require("../assets/fonts/Roboto/static/Roboto-Black.ttf"),
    "Roboto-Italic": require("../assets/fonts/Roboto/static/Roboto-Italic.ttf"),
    Poppins: require("../assets/fonts/Poppins/Poppins-Regular.ttf"),
    "Poppins-Black": require("../assets/fonts/Poppins/Poppins-Black.ttf"),
    "Poppins-BlackItalic": require("../assets/fonts/Poppins/Poppins-BlackItalic.ttf"),
    "Poppins-Bold": require("../assets/fonts/Poppins/Poppins-Bold.ttf"),
    "Poppins-BoldItalic": require("../assets/fonts/Poppins/Poppins-BoldItalic.ttf"),
    "Poppins-ExtraBold": require("../assets/fonts/Poppins/Poppins-ExtraBold.ttf"),
    "Poppins-ExtraBoldItalic": require("../assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf"),
    "Poppins-ExtraLight": require("../assets/fonts/Poppins/Poppins-ExtraLight.ttf"),
    "Poppins-ExtraLightItalic": require("../assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf"),
    "Poppins-Italic": require("../assets/fonts/Poppins/Poppins-Italic.ttf"),
    "Poppins-Light": require("../assets/fonts/Poppins/Poppins-Light.ttf"),
    "Poppins-LightItalic": require("../assets/fonts/Poppins/Poppins-LightItalic.ttf"),
    "Poppins-Medium": require("../assets/fonts/Poppins/Poppins-Medium.ttf"),
    "Poppins-MediumItalic": require("../assets/fonts/Poppins/Poppins-MediumItalic.ttf"),
    "Poppins-SemiBold": require("../assets/fonts/Poppins/Poppins-SemiBold.ttf"),
    "Poppins-SemiBoldItalic": require("../assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf"),
    "Poppins-Thin": require("../assets/fonts/Poppins/Poppins-Thin.ttf"),
    "Poppins-ThinItalic": require("../assets/fonts/Poppins/Poppins-ThinItalic.ttf"),
    Maison: require("../assets/fonts/FontsFree-Net-Maison-Neue-Bold.ttf"),
  },
};
export default resources;
